stages:
  - stage
  - prod

deploy:dev:
  stage: dev
  when: manual
  tags:
    - gcp

  script:
    - docker image prune -af
    - docker builder prune -f
    - echo "Deployment on xplor-stage server."
    - Path=$(pwd)
    - cd /home/ubuntu/script && ./env_script.sh dev Wallet-nest-backend-dev $VAULT_TOKEN && cd $Path
    - mv /home/ubuntu/script/.env $Path
    - |
      sshpass -p $XPLOR_STAGE_PASSWORD ssh $Xplor_Username@$XPLOR_STAGE_IP "
        if [[ -d "$CI_PROJECT_NAME" ]]; then
          cd /home/ubuntu/$CI_PROJECT_NAME
          docker-compose down
          cd /home/ubuntu/ && sudo rm -rf Wallet-nest-backend
        fi "

    - sshpass -p $Xplor_Password ssh $Xplor_Username@$Xplor_IP  "git clone -b feat/certificate-push https://user:'$GITLAB_ACCESS_TOKEN'@gitlab.thewitslab.com/wil-workspace/xplor/Wallet-nest-backend.git"
    - sshpass -p $Xplor_Password scp .env $Xplor_Username@$Xplor_IP:/home/ubuntu/Wallet-nest-backend
    - sshpass -p $Xplor_Password ssh -tt $Xplor_Username@$Xplor_IP  "
        cd /home/ubuntu/Wallet-nest-backend && docker-compose up -d --build "
    - echo "https://xplor-wallet-nest-dev.thewitslab.com"
