stages:
  - stage
  - prod

.deploy-stage:
  stage: stage
  tags:
    - gcp
  script:
    - docker image prune -af
    - docker builder prune -f
    - echo "Deployment on xplor-stage server."
    - Path=$(pwd)
    - cd /home/ubuntu/script && ./env_script.sh staging $CI_PROJECT_NAME-staging $VAULT_TOKEN && cd $Path
    - mv /home/ubuntu/script/.env $Path
    - |
      sshpass -p $XPLOR_STAGE_PASSWORD ssh $Xplor_Username@$XPLOR_STAGE_IP "
        if [[ -d "$CI_PROJECT_NAME" ]]; then
          cd /home/ubuntu/$CI_PROJECT_NAME
          docker-compose down
          cd /home/ubuntu/ && sudo rm -rf $CI_PROJECT_NAME
        fi "

    - sshpass -p $XPLOR_STAGE_PASSWORD ssh $Xplor_Username@$XPLOR_STAGE_IP  "git clone -b main https://user:'$GITLAB_ACCESS_TOKEN'@gitlab.thewitslab.com/wil-workspace/xplor/'$CI_PROJECT_NAME'.git"
    - sshpass -p $XPLOR_STAGE_PASSWORD scp .env $Xplor_Username@$XPLOR_STAGE_IP:/home/ubuntu/$CI_PROJECT_NAME
    - sshpass -p $XPLOR_STAGE_PASSWORD ssh -tt $Xplor_Username@$XPLOR_STAGE_IP  "
        cd /home/ubuntu/$CI_PROJECT_NAME && docker-compose up -d --build "
    - echo "https://xplor-wallet-nest-stage.thewitslab.com" 

deploy-prod:
  stage: prod
  when: manual
  tags:
    - gcp
  script:
    - docker image prune -af
    - docker builder prune -f
    - echo "Deployment on xplor-prod Server."
    - Path=$(pwd)
    - cd /home/ubuntu/script && ./env_script.sh staging $CI_PROJECT_NAME-staging $VAULT_TOKEN && cd $Path
    - mv /home/ubuntu/script/.env $Path
    - |
      sshpass -p $XPLOR_PROD_PASSWORD ssh $Xplor_Username@$XPLOR_PROD_HOST "
        if [[ -d "$CI_PROJECT_NAME" ]]; then
          cd /home/ubuntu/$CI_PROJECT_NAME
          docker-compose -f docker-compose.production.yml down
          cd /home/ubuntu/ && sudo rm -rf $CI_PROJECT_NAME
        fi "
    - sleep 20
    - sshpass -p $XPLOR_PROD_PASSWORD ssh $Xplor_Username@$XPLOR_PROD_HOST "git clone -b main https://user:'$GITLAB_ACCESS_TOKEN'@gitlab.thewitslab.com/wil-workspace/xplor/'$CI_PROJECT_NAME'.git"
    - sshpass -p $XPLOR_PROD_PASSWORD scp -r .env $Xplor_Username@$XPLOR_PROD_HOST:/home/ubuntu/$CI_PROJECT_NAME
    - sshpass -p $XPLOR_PROD_PASSWORD ssh -tt $Xplor_Username@$XPLOR_PROD_HOST "
        cd /home/ubuntu/$CI_PROJECT_NAME && docker-compose -f docker-compose.production.yml up -d --build "
    - echo "HOSTED URL:- https://xplor-wallet-nest-prod.thewitslab.com"
    