stages:
  - dev

deploy:dev:
  stage: dev
  tags:
    - gcp
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" '
      when: on_success
    - when: manual
  script:
    - echo "Deployment on Client Server."
    - Path=$(pwd)
    - cd /home/ubuntu/script && ./env_script.sh dev Wallet-nest-backend-dev $VAULT_TOKEN && cd $Path
    - mv /home/ubuntu/script/.env $Path && cd $Path
    - |
      sshpass -p $Xplor_Password ssh $Xplor_Username@$Xplor_IP "
        if [[ -d Wallet-nest-backend ]]; then
          cd /home/ubuntu/Wallet-nest-backend
          docker-compose down
          cd &&  sudo rm -rf Wallet-nest-backend
        fi "

    - sshpass -p $Xplor_Password ssh $Xplor_Username@$Xplor_IP  "git clone -b develop https://'$GITLAB_ACCESS_TOKEN'@gitlab.thewitslab.com/wil-workspace/xplor/Wallet-nest-backend.git"
    - sshpass -p $Xplor_Passwordd scp -r .env $Xplor_Username@$Xplor_IP:/home/ubuntu/Wallet-nest-backend
    - sshpass -p $Xplor_Password ssh -tt $Xplor_Username@$Xplor_IP  "
        cd /home/ubuntu/Wallet-nest-backend && docker-compose up -d --build "
    - echo "Docker compose up for dev complete"
