export const MaxVCShareHours = 167
export const SELF_ISSUED_SCHEMA_ID = 'SELF_ISSUED_SCHEMA_ID'
export const SELF_ISSUED_SCHEMA_VERSION = 'SELF_ISSUED_SCHEMA_VERSION'
export const SELF_ISSUED_ORGANIZATION_NAME = 'SELF_ISSUED_ORGANIZATION_NAME'
export const SELF_ISSUED_SCHEMA_TAG = 'SELF_ISSUED_SCHEMA_TAG'
export const REGISTRY_SERVICE_URL = 'REGISTRY_SERVICE_URL'
export const WALLET_SERVICE_URL = 'WALLET_SERVICE_URL'
export const REDIS_CLIENT = 'REDIS_CLIENT'
