export default () => ({
  MONGODB_URL: process.env.MONGODB_URL,
  SERVICE_BASE_URL: process.env.SERVICE_BASE_URL,
  STORAGE_BUCKET_NAME: process.env.STORAGE_BUCKET_NAME,
  AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
  SECRET_ACCESS_KEY: process.env.SECRET_ACCESS_KEY,
  STORAGE_REGION: process.env.STORAGE_REGION,
})
