export default () => ({
  MONGODB_URL: process.env.MONGODB_URL,
  STORAGE_BUCKET_NAME: process.env.STORAGE_BUCKET_NAME,
  AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
  SECRET_ACCESS_KEY: process.env.SECRET_ACCESS_KEY,
  STORAGE_REGION: process.env.STORAGE_REGION,
  REGISTRY_SERVICE_URL: process.env.REGISTRY_SERVICE_URL,
  WALLET_SERVICE_URL: process.env.WALLET_SERVICE_URL,
  REDIS_HOST: process.env.REDIS_HOST,
  REDIS_PORT: process.env.REDIS_PORT,
  REDIS_SERVICE_NAME: process.env.REDIS_SERVICE_NAME,
  REDIS_PASSWORD: process.env.REDIS_PASSWORD,
  URL_SHORTENER_SERVICE_URL: process.env.URL_SHORTENER_SERVICE_URL,
})
